# Generated by Django 4.1.7 on 2023-03-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('nit', models.PositiveIntegerField()),
                ('tax_responsibility', models.CharField(max_length=255)),
                ('taxpayer_type', models.CharField(max_length=255)),
                ('responsibility_type', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=10)),
                ('billing_email', models.EmailField(max_length=254)),
                ('sales_contact', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
